# /data/adb/modules/thermal_mod/thermal.conf
# -----------------------------------------------------------------------------
# Quick command to check all available cooling devices on the device (can be copied and run directly in adb shell):
# for d in /sys/class/thermal/cooling_device*; do [ -d "$d" ] && echo "${d##*/}: $(cat "$d/type" 2>/dev/null || echo 'N/A'): $(cat "$d/max_state" 2>/dev/null || echo '0')"; done
# example: "cooling_device0: cpu-cluster0: 25"
# -----------------------------------------------------------------------------

[global]
poll_interval = 2
temp_path = /sys/class/thermal/thermal_zone0/temp

[cooling_0]
path = /sys/class/thermal/cooling_device0/cur_state
80000 = 16
65000 = 8
50000 = 4

[cooling_1]
path = /sys/class/thermal/cooling_device1/cur_state
80000 = 16
65000 = 8
50000 = 4

[cooling_2]
path = /sys/class/thermal/cooling_device2/cur_state
80000 = 16
65000 = 8
50000 = 4

[cooling_10]
path = /sys/class/thermal/cooling_device10/cur_state
80000 = 6
65000 = 3
50000 = 2